//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Net_webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int ID { get; set; }
        public string TenBaiViet { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayViet { get; set; }
        public string NguoiViet { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<bool> HienThi { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public Nullable<int> idBaiViet { get; set; }
    
        public virtual LoaiBaiViet LoaiBaiViet { get; set; }
    }
}
