//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Net_webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int ID { get; set; }
        public string TenKhachHang { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> idLoaiKhachHang { get; set; }
    
        public virtual LoaiKhachHang LoaiKhachHang { get; set; }
    }
}
