//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Net_webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayTinh
    {
        public int ID { get; set; }
        public string TenMayTinh { get; set; }
        public string HangSanXuat { get; set; }
        public Nullable<int> NamSanXuat { get; set; }
    }
}
