//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Net_webApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BanHang_TestEntities1 : DbContext
    {
        public BanHang_TestEntities1()
            : base("name=BanHang_TestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiViet> BaiViets { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiBaiViet> LoaiBaiViets { get; set; }
        public virtual DbSet<LoaiKhachHang> LoaiKhachHangs { get; set; }
        public virtual DbSet<MayTinh> MayTinhs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<spDanhSachKhachHang_Result> spDanhSachKhachHang(string fitter, Nullable<int> idLoaKh)
        {
            var fitterParameter = fitter != null ?
                new ObjectParameter("fitter", fitter) :
                new ObjectParameter("fitter", typeof(string));
    
            var idLoaKhParameter = idLoaKh.HasValue ?
                new ObjectParameter("idLoaKh", idLoaKh) :
                new ObjectParameter("idLoaKh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDanhSachKhachHang_Result>("spDanhSachKhachHang", fitterParameter, idLoaKhParameter);
        }
    }
}
